name: vn_badwords_filter
description: A Dart package to filter and clean bad words in Vietnamese language.
version: 1.0.2
homepage: https://github.com/kreazyme/vn_badwords_filter

environment:
  sdk: ^3.0.0
dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
